### ISSUE TITLE
Cannot read property 'toLocaleString' of null

### ISSUE THREAD

**Issue by Cheizr** [sanchezmarcos/binance-p2p-bot#2]
Hola, gracias por compartir tu bot, estaba probandolo y después seleccionar las opciones me devuelve lo siguiente:

```
3️⃣  Processed results

(node:10236) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLocaleString' of null
    at C:\Users\------\AppData\Roaming\npm\node_modules\binance-p2p-bot\index.js:55:69
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sanchezmarcos** [comment]
Hola! cómo estás? 
Ya esta solucionado el problema, muchas gracias por avisar. 😊
Proba con la versión 0.0.9 y contame.
Saludos!
